Attempt to fix the shuttle test
Before this change, the test didn't work conceptually, because:

1) `TokenBucket` was initialized with 10 tokens.
2) After first successful consumption, there were 0 tokens left.
3) The refill rate of 1000 t/s means that in 2000 us, only 2 tokens
   are refilled (2000 us * 0.001 t/us = 2 tokens).
4) Each consumption needs 10 tokens.
5) 2000 us is not enough for more than one successful consumption to
   happen.

Furthermore, the test didn't work practically, because the time
advancement wasn't properly simulated. Time was advanced only when a
successful consumption of a token happened. Since there was only one
successful consumption happening, the timeout of 2000 us was never
reached.

That was the reason why the test failure was mentioning exceeding the
maximum number of steps and porential of a spin loop:

```
thread 'token_bucket::test::shuttle_test_token_bucket_race' panicked at shuttle-0.7.1/src/runtime/execution.rs:203:17:
exceeded max_steps bound 1000000. this might be caused by an unfair schedule (e.g., a spin loop)?
failing schedule
```

The condition `while run.load(Ordering::SeqCst)` was never broken, so
the loop was running indefinitely.

Also, there were other minor problems or nits to fix:

1) `std::sync::atomic::AtomicBool` was used in a shuttle test, even
  imported directly there.
2) `TIME_US` was unnecessarily wrapped in `OnceLock`.

Attempt to fix the test by picking more realistic parameters:

* initial tokens: 10
* refill rate: 5000 t/s (5 t/ms)
* consumption of 5 tokens

Which in 2 ms produces 10 + (5 * 2) = 20 tokens.

With this amount, 4 consumptions of 5 tokens can happen.

Fix the minor issues by:

1) Using `solana_svm_type_overrides`, which provides a layer that takes
   care of importing from `std::sync`, `std::thread`, `shuttle::sync`,
   `shuttle::thread` with appropriate feature flags.
2) Just using the `AtomicU64` directly.